# Generated by Django 3.0.3 on 2020-03-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='detail',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patient',
            name='first_name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_name',
            field=models.TextField(max_length=30),
        ),
    ]
